name: qrscout
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.4
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  font_awesome_flutter: ^10.2.1
  camera: ^0.10.0+4
  firebase_storage: ^11.0.6
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  photo_view: ^0.14.0
  flutter_share: ^2.0.0
  http: ^0.13.5
  share_extend: ^2.0.0
  settings_ui: ^2.0.2
  firebase_database: ^10.0.6
  # google_sign_in: 5.3.3
  # sign_in_with_apple: 4.0.0
  # crypto: 3.0.1
  # font_awesome_flutter: 10.1.0
  # google_fonts: 3.0.1
  # provider: 6.0.3
  # rxdart: 0.27.4
  # json_annotation: 4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # build_runner: 2.1.11
  # json_serializable: 6.2.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/
  #   - assets/covers/
  #   - assets/congrats.gif